# Generated by Django 5.1.1 on 2024-09-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(to='blog.actors'),
        ),
    ]
