# Generated by Django 5.1.1 on 2024-09-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_movies_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='date_of_birth',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.TextField(default='', max_length=400),
        ),
    ]
